<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title', 'Admin') · Mahj</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root{--orange:#EC5D01;--ink:#0D1328;--muted:#667085;--line:#EAECF0;--bg:#F7F8FA;--white:#fff;--danger:#EF4444;--success:#16803A}
        *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,system-ui,sans-serif;font-size:14px}a{text-decoration:none;color:inherit}button,input,select{font:inherit}
        .app{display:grid;grid-template-columns:250px 1fr;min-height:100vh}.side{position:sticky;top:0;height:100vh;background:#fff;border-right:1px solid var(--line);padding:24px 18px;display:flex;flex-direction:column}.brand{display:flex;align-items:center;gap:11px;font-weight:700;font-size:21px;padding:0 8px 26px}.logo{width:38px;height:38px;border-radius:12px;background:var(--orange);color:#fff;display:grid;place-items:center;box-shadow:0 8px 20px rgba(236,93,1,.22)}
        .nav-label{padding:0 10px 8px;color:#98A2B3;font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.nav{display:grid;gap:6px}.nav a{padding:12px 13px;border-radius:12px;color:var(--muted);font-weight:600}.nav a:hover,.nav a.active{background:#FFF0E6;color:var(--orange)}.admin-box{margin-top:auto;border:1px solid var(--line);border-radius:13px;padding:12px}.admin-box b{display:block;font-size:12px}.admin-box span{display:block;margin-top:3px;color:var(--muted);font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.logout{width:100%;height:40px;margin-top:10px;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--ink);font-weight:600;cursor:pointer}
        .main{min-width:0}.top{height:76px;background:rgba(255,255,255,.95);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 30px;position:sticky;top:0;z-index:5}.title{font-size:20px;font-weight:700}.subtitle{font-size:12px;color:var(--muted);margin-top:4px}.admin-badge{padding:8px 11px;border:1px solid var(--line);border-radius:999px;background:#fff;font-size:11px;font-weight:600}.content{max-width:1400px;margin:0 auto;padding:28px 30px 48px}
        .flash,.errors{padding:12px 14px;border-radius:11px;margin-bottom:18px}.flash{background:#ECFDF3;color:#027A48;border:1px solid #ABEFC6}.errors{background:#FEF3F2;color:#B42318;border:1px solid #FECDCA}
        .stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:22px}.stat,.card{background:#fff;border:1px solid var(--line);border-radius:18px;box-shadow:0 5px 18px rgba(13,19,40,.035)}.stat{padding:18px}.stat .label{color:var(--muted);font-size:11px;font-weight:600}.stat .value{font-size:29px;font-weight:700;margin-top:9px}.stat .note{font-size:10px;color:#98A2B3;margin-top:6px}
        .grid2{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card-pad{padding:20px}.card-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:16px}.card-title{font-size:16px;font-weight:700}.card-copy{color:var(--muted);font-size:11px;line-height:1.55;margin-top:5px}
        .quick{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:20px;background:#fff;border:1px solid var(--line);border-radius:18px}.quick:hover{border-color:#F4CDB5;box-shadow:0 8px 24px rgba(13,19,40,.06)}.quick b{display:block}.quick span{display:block;color:var(--muted);font-size:11px;margin-top:4px}.quick-icon{width:46px;height:46px;border-radius:14px;background:#FFF0E6;color:var(--orange);display:grid;place-items:center;font-size:19px;font-weight:700}.quick-main{display:flex;align-items:center;gap:13px}
        .toolbar{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:16px}.search{display:flex;gap:8px;max-width:470px;width:100%}.input,.select{width:100%;height:43px;border:1px solid #D0D5DD;border-radius:11px;padding:0 13px;background:#fff;color:var(--ink);outline:none}.input:focus,.select:focus{border-color:var(--orange);box-shadow:0 0 0 3px rgba(236,93,1,.1)}.btn{height:43px;border:0;border-radius:11px;padding:0 15px;background:var(--orange);color:#fff;font-weight:600;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;white-space:nowrap}.btn-secondary{background:#fff;color:var(--ink);border:1px solid #D0D5DD}.btn-soft{background:#FFF0E6;color:var(--orange)}.btn-danger{background:#fff;color:var(--danger);border:1px solid #FECDCA}
        .table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;min-width:760px}.table th{text-align:left;padding:11px 15px;background:#FCFCFD;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid var(--line)}.table td{padding:14px 15px;border-bottom:1px solid #F2F4F7}.table tr:last-child td{border-bottom:0}.user{display:flex;align-items:center;gap:10px}.avatar{width:38px;height:38px;border-radius:12px;background:#FFF0E6;color:var(--orange);display:grid;place-items:center;font-weight:700}.user b{display:block;font-size:12px}.user span{display:block;color:var(--muted);font-size:10px;margin-top:3px}.badge{display:inline-flex;padding:6px 9px;border-radius:999px;background:#F2F4F7;color:#475467;font-size:10px;font-weight:700}.badge.success{background:#ECFDF3;color:#027A48}.badge.warning{background:#FFFAEB;color:#B54708}.badge.danger{background:#FEF3F2;color:#B42318}.badge.orange{background:#FFF0E6;color:var(--orange)}
        .back{display:inline-block;margin-bottom:15px;color:var(--muted);font-size:11px;font-weight:600}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.span2{grid-column:span 2}.field label{display:block;margin-bottom:7px;font-size:11px;font-weight:600;color:#475467}.field small{display:block;margin-top:6px;color:#98A2B3;font-size:10px;line-height:1.45}.switch-row{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:13px;border:1px solid var(--line);border-radius:12px;background:#FCFCFD}.switch-row b{display:block;font-size:12px}.switch-row span{display:block;color:var(--muted);font-size:10px;margin-top:4px}.switch{width:42px;height:24px;appearance:none;background:#D0D5DD;border-radius:99px;position:relative;cursor:pointer}.switch:before{content:"";position:absolute;width:18px;height:18px;background:#fff;border-radius:50%;left:3px;top:3px;transition:.2s;box-shadow:0 1px 3px rgba(0,0,0,.15)}.switch:checked{background:var(--orange)}.switch:checked:before{transform:translateX(18px)}
        .profile{display:flex;align-items:center;gap:14px}.profile .big-avatar{width:56px;height:56px;border-radius:16px;background:#FFF0E6;color:var(--orange);display:grid;place-items:center;font-size:20px;font-weight:700}.profile h2{margin:0;font-size:18px}.profile p{margin:5px 0 0;color:var(--muted);font-size:11px}.meta{display:grid;gap:11px}.meta-row{display:flex;justify-content:space-between;gap:16px;padding-bottom:10px;border-bottom:1px solid #F2F4F7}.meta-row:last-child{border-bottom:0;padding-bottom:0}.meta-row span{color:var(--muted);font-size:11px}.meta-row b{font-size:11px;text-align:right}
        .plan-hero{display:grid;grid-template-columns:1fr auto;gap:16px;align-items:center;padding:20px;border-radius:16px;background:linear-gradient(135deg,#0D1328,#1F2B4A);color:#fff;margin-bottom:16px}.plan-hero .eyebrow{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#C7CEDD;font-weight:700}.plan-hero h3{margin:7px 0 4px;font-size:20px}.plan-hero p{margin:0;color:#CBD1DE;font-size:11px}.price{font-size:26px;font-weight:700;text-align:right}.price span{display:block;color:#CBD1DE;font-size:10px;font-weight:500;margin-top:4px}.hint{padding:12px 13px;border-radius:11px;background:#FFF8F3;color:#8A3B09;border:1px solid #F7DCCB;font-size:11px;line-height:1.55}.empty{padding:28px;text-align:center;color:var(--muted)}
        details{border:1px solid var(--line);border-radius:12px;padding:12px 13px;background:#FCFCFD}summary{cursor:pointer;font-size:11px;font-weight:600;color:#475467}.details-body{padding-top:13px}
        @media(max-width:1000px){.stats{grid-template-columns:1fr 1fr}.grid2{grid-template-columns:1fr}}@media(max-width:760px){.app{grid-template-columns:1fr}.side{position:static;height:auto;padding:14px;border-right:0;border-bottom:1px solid var(--line)}.brand{padding:0 4px 13px}.nav-label,.admin-box{display:none}.nav{grid-template-columns:repeat(5,1fr)}.nav a{text-align:center;padding:9px 5px;font-size:10px}.top{position:static;height:auto;padding:15px 17px}.admin-badge{display:none}.content{padding:18px 15px 36px}.stats{grid-template-columns:1fr 1fr;gap:10px}.stat{padding:15px}.stat .value{font-size:24px}.toolbar{flex-direction:column;align-items:stretch}.search{max-width:none}.form-grid{grid-template-columns:1fr}.span2{grid-column:auto}.plan-hero{grid-template-columns:1fr}.price{text-align:left}}
    </style>
</head>
<body>
<div class="app">
    <aside class="side">
        <a class="brand" href="{{ route('admin.dashboard') }}"><span class="logo">M</span>Mahj Admin</a>
        <div class="nav-label">Management</div>
        <nav class="nav">
            <a class="{{ request()->routeIs('admin.dashboard') ? 'active' : '' }}" href="{{ route('admin.dashboard') }}">Overview</a>
            <a class="{{ request()->routeIs('admin.users*') ? 'active' : '' }}" href="{{ route('admin.users') }}">Users</a>
            <a class="{{ request()->routeIs('admin.matches*') ? 'active' : '' }}" href="{{ route('admin.matches') }}">Matches</a>
            <a class="{{ request()->routeIs('admin.sports*') ? 'active' : '' }}" href="{{ route('admin.sports') }}">Sports</a>
            <a class="{{ request()->routeIs('admin.subscriptions*') || request()->routeIs('admin.plans*') ? 'active' : '' }}" href="{{ route('admin.subscriptions') }}">Subscriptions</a>
        </nav>
        <div class="admin-box"><b>{{ auth()->user()->name }}</b><span>{{ auth()->user()->email }}</span><form method="post" action="{{ route('admin.logout') }}">@csrf<button class="logout" type="submit">Log out</button></form></div>
    </aside>
    <main class="main">
        <header class="top"><div><div class="title">@yield('title')</div><div class="subtitle">@yield('subtitle')</div></div><div class="admin-badge">Admin access</div></header>
        <div class="content">
            @if(session('status'))<div class="flash">{{ session('status') }}</div>@endif
            @if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
            @yield('content')
        </div>
    </main>
</div>
</body>
</html>
